version: 2.1

jobs:        
    machine:
      - image: "ubuntu-1604:201903-01"

    steps:
      - checkout

      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc g++'

      - run:
          name: Installing Build Essential
          command: 'sudo apt-get update && sudo apt-get install -y build-essential'

      - run:
          name: Check GCC version
          command: 'gcc --version'
          
      - run:
          name: Build project
          command: 'gcc ./OWI_Code_Sample/Main.cpp -Wall -g -o owi_sample -lstdc++ -std=c++17'
          
      - run:
          name: Installing Valgrind
          command: 'apt-get update && apt-get install -y valgrind'
          
      - run:
          name: Valgrind Test
          command: 'valgrind ./owi_sample'
      
workflows:
  version: 2
  build:
    jobs:
      - build
