version: 2

jobs:
  build:
    branches:
      only:
        - master
        
    docker:
      - image: debian:stretch
      
    steps:
      - checkout
      
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
          
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y clang-7'

      - run:
          name: Check GCC version
          command: 'g++ --version'
          
      - run:
          name: Build project
          command: 'g++ ./OWI_Code_Sample/Main.cpp -Wall -g -o owi_sample -lstdc++'

      - run:
          name: Installing Valgrind
          command: 'apt-get update && apt-get install -y valgrind'
          
      - run:
          name: Valgrind Test
          command: 'valgrind ./owi_sample'
