version: 2

jobs:
  build:
    branches:
      only:
        - master
        
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
         
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc-7 g++-7'
         
      - run:
          name: Configure C++ version
          command: 'export CC=gcc-7 && export CXX=g++-7'
         
      - run:
          name: Check G++ version
          command: 'g++ --version'
          
      - run:
          name: Build project
          command: 'g++ ./OWI_Code_Sample/Main.cpp -Wall -g -o owi_sample -std=c++17'
          
      - run:
          name: Installing Valgrind
          command: 'apt-get update && apt-get install -y valgrind'
          
      - run:
          name: Valgrind Test
          command: 'valgrind ./owi_sample'
