version: 2

jobs:
  build:
    branches:
      only:
        - master
        
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
         
      - run:
          name: Installing GCC
          command: 'sudo apt-get -y update && sudo apt-get -y install software-properties-common && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get -y update && sudo apt-get -y install -y gcc g++ libtool autoconf automake cmake gcc-8 g++-8'
         
      - run:
          name: Check C++ version
          command: 'export CC=gcc-8 && export CXX=g++-8 && $CXX --version'
          
      - run:
          name: Build project
          command: 'export CC=gcc-8 && export CXX=g++-8 && $CXX ./OWI_Code_Sample/Main.cpp -Wall -Wextra -O3 -g -fPIE -o owi_sample -std=c++17'
          
      - run:
          name: Installing Valgrind
          command: 'sudo apt-get update && sudo apt-get install -y valgrind
          && sudo wget sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2
          && tar -xjf valgrind-3.13.0.tar.bz2 && cd valgrind-3.13.0/
          && ./configure && make
          && sudo make install
          && sudo whereis valgrind
          && sudo update-alternatives --install /usr/bin/valgrind valgrind /usr/local/bin/valgrind 1 --force
          && ll /usr/bin/valgrind
          && ll /etc/alternatives/valgrind
          && valgrind --version'
          
      - run:
          name: Valgrind Test
          command: 'valgrind --help && valgrind --run-cxx-freeres=yes --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --error-exitcode=1 ./owi_sample'
