version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Build project
          command: gcc ./OWI_Code_Sample/Main.cpp -Wall -g -o owi_sample -lstdc++ -std=gnu++17

      - run:
          name: Valgrind Test
          command: valgrind ./owi_sample
      
workflows:
  version: 2
  build:
    jobs:
      - build