version: 2

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019

    steps:
      - checkout

      - run:
          name: Building VS Project
          command: 'msbuild OWI_Code_Sample.sln -O3'
      
workflows:
  version: 2
  build:
    jobs:
      - build
