version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: install g++
          command: apt -y install g++

      - run:
          name: build project
          command: gcc-6-base ./OWI_Code_Sample/Main.cpp -Wall -g -o owi_sample -lstdc++ -std=gnu++17
workflows:
  version: 2
  build:
    jobs:
      - build