version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    branches:
      only:
        - master
    
    executor: win/vs2019
    
    steps:
      - checkout
      - run: 'msbuild ./OWI_Code_Sample/OWI_Code_Sample.vcxproj /p:configuration=debug /std:c++latest'

