version: 2

jobs:
  build:
    branches:
      only:
        - master
        
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
         
      - run:
          name: Installing GCC
          command: 'sudo apt-get -y update && sudo apt-get -y install software-properties-common && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get -y update && sudo apt-get -y install -y gcc g++ libtool autoconf automake cmake gcc-8 g++-8'
         
      - run:
          name: Check C++ version
          command: 'export CC=gcc-8 && export CXX=g++-8 && $CXX --version'
          
      - run:
          name: Build project
          command: 'export CC=gcc-8 && export CXX=g++-8 && $CXX ./OWI_Code_Sample/Main.cpp -Wall -Wextra -O0 -g -fPIE -o owi_sample -std=c++17'
          
      - run:
          name: Installing Valgrind
          command: 'sudo apt-get update && sudo apt-get install -y valgrind'
          
      - run:
          name: Valgrind Test
          command: 'valgrind --leak-check=full --show-leak-kinds=all ./owi_sample'
