version: 2

jobs:
  build:
    branches:
      only:
        - master
        
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
         
      - run:
          name: Installing GCC
          command: 'sudo apt-get -y update && sudo apt-get -y install software-properties-common && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get -y update && sudo apt-get -y install -y gcc g++ libtool autoconf automake cmake gcc-8 g++-8'
         
      - run:
          name: Check C++ version
          command: 'export CC=gcc-8 && export CXX=g++-8 && $CXX --version'
          
      - run:
          name: Build project
          command: 'export CC=gcc-8 && export CXX=g++-8 && $CXX ./OWI_Code_Sample/Main.cpp -Wall -Wextra -O3 -g -fPIE -o owi_sample -std=c++17'
          
      - run:
          name: Installing Valgrind
          command: 'sudo apt-get update && sudo apt-get install -y valgrind \
          && sudo wget ftp://sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2 \
          && tar -xjf valgrind-3.13.0.tar.bz2 && cd valgrind-3.13.0/ \
          && ./configure && make \
          && sudo make install \
          && sudo whereis valgrind \
valgrind: /usr/bin/valgrind.bin /usr/bin/valgrind /usr/lib/valgrind /usr/bin/X11/valgrind.bin /usr/bin/X11/valgrind /usr/local/bin/valgrind /usr/local/lib/valgrind /usr/include/valgrind /usr/share/man/man1/valgrind.1.gz \
          && sudo update-alternatives --install /usr/bin/valgrind valgrind /usr/local/bin/valgrind 1 --force \
update-alternatives: using /usr/local/bin/valgrind to provide /usr/bin/valgrind in auto mode \
          && ll /usr/bin/valgrind
lrwxrwxrwx 1 root root 26 Sep  3 09:34 /usr/bin/valgrind -> /etc/alternatives/valgrind \
          && ll /etc/alternatives/valgrind \
lrwxrwxrwx 1 root root 23 Sep  3 09:34 /etc/alternatives/valgrind -> /usr/local/bin/valgrind \
          && valgrind --version'
          
      - run:
          name: Valgrind Test
          command: 'valgrind --help && valgrind --run-cxx-freeres=yes --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --error-exitcode=1 ./owi_sample'
